title: Drinky Yan Homepage
page-top-title: Drinky Yan Homepage
top-section-bg-text: A 50%-50% hustle and chill average joe dreaming of hitting the jackpot one day...
home-subtitle: Drinky Yan
copyright-text: '&copy; Jerry Yin 2024. All Rights Reserved. Template by Jerry Yin From <a href="https://github.com/JerryYin777/JerryYin777.github.io">This Repo</a>.'
